package com.njagakneai.panjalupdf.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF04162C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF1A2B42)
val md_theme_light_onPrimaryContainer = Color(0xFF8292AE)
val md_theme_light_secondary = Color(0xFFA83442)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFE757F)
val md_theme_light_onSecondaryContainer = Color(0xFF72081E)
val md_theme_light_tertiary = Color(0xFF121719)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF272B2D)
val md_theme_light_onTertiaryContainer = Color(0xFF8E9295)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF9F9FF)
val md_theme_light_onBackground = Color(0xFF111C2C)
val md_theme_light_surface = Color(0xFFF9F9FF)
val md_theme_light_onSurface = Color(0xFF111C2C)
val md_theme_light_surfaceVariant = Color(0xFFD8E3FA)
val md_theme_light_onSurfaceVariant = Color(0xFF44474D)
val md_theme_light_outline = Color(0xFF74777E)
val md_theme_light_inverseOnSurface = Color(0xFFEBF1FF)
val md_theme_light_inverseSurface = Color(0xFF263142)
val md_theme_light_inversePrimary = Color(0xFFB6C7E5)

// Define basic dark theme based on inverse logic or defaults if not strictly specified
val md_theme_dark_primary = Color(0xFFB6C7E5)
val md_theme_dark_onPrimary = Color(0xFF04162C)
val md_theme_dark_primaryContainer = Color(0xFF1A2B42)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFFFFB3B5)
val md_theme_dark_onSecondary = Color(0xFF40000B)
val md_theme_dark_secondaryContainer = Color(0xFF72081E)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADA)
val md_theme_dark_tertiary = Color(0xFFC3C7CA)
val md_theme_dark_onTertiary = Color(0xFF181C1E)
val md_theme_dark_tertiaryContainer = Color(0xFF272B2D)
val md_theme_dark_onTertiaryContainer = Color(0xFFE0E3E6)
val md_theme_dark_error = Color(0xFFFFDAD6)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111C2C)
val md_theme_dark_onBackground = Color(0xFFF9F9FF)
val md_theme_dark_surface = Color(0xFF111C2C)
val md_theme_dark_onSurface = Color(0xFFF9F9FF)
val md_theme_dark_surfaceVariant = Color(0xFF44474D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CD)
val md_theme_dark_outline = Color(0xFF74777E)
val md_theme_dark_inverseOnSurface = Color(0xFF111C2C)
val md_theme_dark_inverseSurface = Color(0xFFF9F9FF)
val md_theme_dark_inversePrimary = Color(0xFF04162C)
